variable "instance_type" {
  type        = string
  description = "The type of instance to launch."
  default     = "t3.small"
}

variable "aws_region" {
  type        = string
  description = "The AWS region to deploy to."
  default     = "us-east-1"
}

variable "name_prefix" {
  type        = string
  description = "The prefix to apply to the beginning of names generated by this module."
}

variable "tags" {
  type        = map(string)
  description = "Key/Value pairs to pass to AWS as Tags."
  default     = {}
}